from __future__ import annotations

import json
import posixpath
from collections import Counter
from html import escape

from .config import TaskosConfig
from .model import STATUS_LABELS, STATUS_ORDER, Task, ready_tasks, status_by_id


def format_dependencies(task: Task) -> str:
    dependencies = [str(dependency) for dependency in task.get("dependencies", [])]
    return ", ".join(f"`{dependency}`" for dependency in dependencies) if dependencies else "None"


def markdown_list(title: str, values: object) -> list[str]:
    if not values:
        return []
    result = ["", f"{title}:"]
    if isinstance(values, list):
        result.extend(f"- {value}" for value in values)
    else:
        result.append(str(values))
    return result


def ordered_task_ids(task_ids: set[str], _tasks: list[Task]) -> list[str]:
    def sort_key(task_id: str) -> tuple[int, int | str]:
        prefix, separator, suffix = task_id.rpartition("-")
        if prefix == "TASK" and separator and suffix.isdigit():
            return (0, int(suffix))
        return (1, task_id)

    return sorted(task_ids, key=sort_key)


def format_dependency_groups(task: Task, statuses: dict[str, str], tasks: list[Task]) -> list[str]:
    dependencies = [str(dependency) for dependency in task.get("dependencies", [])]
    if not dependencies:
        return ["- Dependencies: none"]

    done = [dependency for dependency in dependencies if statuses.get(dependency) == "done"]
    open_dependencies = [
        dependency
        for dependency in dependencies
        if dependency not in done and dependency in statuses
    ]
    missing = [dependency for dependency in dependencies if dependency not in statuses]

    lines = ["- Dependencies:"]
    if open_dependencies:
        lines.append(
            "  - open: "
            + ", ".join(f"`{dependency}` ({statuses[dependency]})" for dependency in open_dependencies)
        )
    if done:
        ordered_done = ordered_task_ids(set(done), tasks)
        lines.append("  - done ids: " + ", ".join(f"`{dependency}`" for dependency in ordered_done))
    if missing:
        lines.append("  - missing: " + ", ".join(f"`{dependency}`" for dependency in missing))
    return lines


def generated_active_tasks(config: TaskosConfig, tasks: list[Task]) -> str:
    ready = ready_tasks(tasks, config.priority_order)
    ready_ids = {str(task["id"]) for task in ready}
    statuses = status_by_id(tasks)
    counts = Counter(str(task.get("status", "")) for task in tasks)
    active_tasks = [task for task in tasks if task.get("status") != "done"]
    done_dependency_ids = {
        str(dependency)
        for task in active_tasks
        for dependency in task.get("dependencies", [])
        if statuses.get(str(dependency)) == "done"
    }
    waiting_pending_count = max(0, counts.get("pending", 0) - len(ready_ids))

    sections: dict[str, list[Task]] = {
        "in_progress": [],
        "ready": [],
        "blocked": [],
        "pending": [],
    }
    for task in active_tasks:
        status = str(task.get("status", "pending"))
        bucket = "ready" if str(task["id"]) in ready_ids else status
        sections.setdefault(bucket, []).append(task)

    lines = [
        f"# Active Tasks: {config.project_name}",
        "",
        f"Generated from `{config.tasks_file}` by `{config.command_name} sync`. Do not edit this file manually.",
        f"Use this compact view for ordinary task orientation. `{config.tasks_file}` remains the canonical full dependency graph; `{config.progress_file}` remains the completion log.",
        "",
        "## Summary",
        "",
        f"- Total tasks in graph: {len(tasks)}",
        f"- Active tasks shown here: {len(active_tasks)}",
        f"- Done tasks hidden here: {counts.get('done', 0)}",
        f"- In progress: {counts.get('in_progress', 0)}",
        f"- Blocked: {counts.get('blocked', 0)}",
        f"- Can start now / dependency-ready pending: {len(ready_ids)}",
        f"- Pending but waiting on dependencies: {waiting_pending_count}",
        f"- Done dependency ids referenced by active tasks: {len(done_dependency_ids)}",
        "",
        "Ready to start now:",
        *([f"- `{task['id']}` - {task.get('title', '')}" for task in ready] or ["- _None._"]),
        "",
        "Done dependency ids referenced by active tasks:",
        *(
            [
                "- " + ", ".join(f"`{task_id}`" for task_id in ordered_task_ids(done_dependency_ids, tasks))
            ]
            if done_dependency_ids
            else ["- _None._"]
        ),
    ]

    section_titles = {
        "in_progress": "In Progress",
        "ready": "Dependency Ready",
        "blocked": "Blocked",
        "pending": "Pending / Waiting",
    }
    for bucket in ("in_progress", "ready", "blocked", "pending"):
        bucket_tasks = sections.get(bucket, [])
        lines.extend(["", f"## {section_titles[bucket]}", ""])
        if not bucket_tasks:
            lines.append("_No tasks._")
            continue
        for task in bucket_tasks:
            status = "dependency-ready" if bucket == "ready" else task.get("status", "")
            lines.extend(
                [
                    f"### {task['id']} - {task.get('title', '')}",
                    "",
                    f"- Status: `{status}`",
                    f"- Priority: `{task.get('priority', '')}`",
                    f"- Category: `{task.get('category', '')}`",
                    f"- Stage: `{task.get('stage', '')}`",
                    f"- Stage gate: `{bool(task.get('stage_gate', False))}`",
                    *format_dependency_groups(task, statuses, tasks),
                ]
            )
            description = str(task.get("description", "")).strip()
            if description:
                lines.extend(["", "Goal:", "", description])
            lines.extend(markdown_list("Scope", task.get("scope")))
            lines.extend(markdown_list("Acceptance", task.get("acceptance_criteria")))
            lines.extend(markdown_list("Test Steps", task.get("test_steps")))
            notes = str(task.get("notes", "")).strip()
            if notes:
                lines.extend(["", "Notes:", "", notes])
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def generated_kanban(config: TaskosConfig, tasks: list[Task]) -> str:
    ready_ids = {str(task["id"]) for task in ready_tasks(tasks, config.priority_order)}
    counts = Counter(str(task.get("status", "")) for task in tasks)
    stage_counts = Counter(str(task.get("stage", "Unstaged")) for task in tasks)
    gate_tasks = [task for task in tasks if task.get("stage_gate")]
    in_progress_tasks = [task for task in tasks if task.get("status") == "in_progress"]
    blocked_tasks = [task for task in tasks if task.get("status") == "blocked"]
    waiting_pending_count = max(0, counts.get("pending", 0) - len(ready_ids))
    sections: dict[str, list[Task]] = {status: [] for status in STATUS_ORDER}
    for task in tasks:
        status = str(task.get("status", "pending"))
        bucket = "ready" if str(task["id"]) in ready_ids else status
        sections.setdefault(bucket, []).append(task)

    lines = [
        f"# Kanban: {config.project_name}",
        "",
        f"Generated from `{config.tasks_file}` by `{config.command_name} sync`. Do not edit this file manually.",
        f"Use `{config.command_name} claim`, `done`, `block`, `release`, or `sync` instead.",
        "",
        "## Summary",
        "",
        f"- Total tasks: {len(tasks)}",
        f"- Done: {counts.get('done', 0)}",
        f"- In progress: {counts.get('in_progress', 0)}",
        f"- Blocked: {counts.get('blocked', 0)}",
        f"- Can start now / dependency-ready pending: {len(ready_ids)}",
        f"- Pending but waiting on dependencies: {waiting_pending_count}",
        f"- Pending total: {counts.get('pending', 0)}",
        f"- Stage gates: {len(gate_tasks)}",
        "",
        "Ready to start now:",
        *(
            [
                f"- `{task['id']}` - {task.get('title', '')}"
                for task in ready_tasks(tasks, config.priority_order)
            ]
            or ["- _None._"]
        ),
        "",
        "In progress now:",
        *(
            [
                f"- `{task['id']}` - {task.get('title', '')}"
                for task in in_progress_tasks
            ]
            or ["- _None._"]
        ),
        "",
        "Blocked / launch-risk:",
        *(
            [
                f"- `{task['id']}` - {task.get('title', '')}"
                for task in blocked_tasks
            ]
            or ["- _None._"]
        ),
        "",
        "Stage summary:",
        *[
            f"- `{stage}` - {count} task(s)"
            for stage, count in sorted(stage_counts.items())
        ],
        "",
        "Stage gates:",
        *[
            f"- `{task['id']}` - {task.get('stage', '')} - {task.get('status', '')}"
            for task in gate_tasks
        ],
        "",
        "## Legend",
        "",
        "- `pending` - not started.",
        "- `in_progress` - claimed by a chat or worker.",
        "- `blocked` - blocked by missing credentials, services, or decisions.",
        "- `done` - completed and verified enough for its scope.",
        "- `dependency-ready` / `can start` - pending with all dependencies done.",
        "- Dashboard colors: bright orange means can start now, blue means in work, green means done, red means blocked, gray means waiting.",
    ]

    for bucket in STATUS_ORDER:
        bucket_tasks = sections.get(bucket, [])
        lines.extend(["", f"## {STATUS_LABELS[bucket]}", ""])
        if not bucket_tasks:
            lines.append("_No tasks._")
            continue
        for task in bucket_tasks:
            status = "dependency-ready" if bucket == "ready" else task.get("status", "")
            lines.extend(
                [
                    f"### {task['id']} - {task.get('title', '')}",
                    "",
                    f"Status: `{status}`",
                    f"Priority: `{task.get('priority', '')}`",
                    f"Category: `{task.get('category', '')}`",
                    f"Stage: `{task.get('stage', '')}`",
                    f"Stage gate: `{bool(task.get('stage_gate', False))}`",
                    f"Dependencies: {format_dependencies(task)}",
                ]
            )
            description = str(task.get("description", "")).strip()
            if description:
                lines.extend(["", "Goal:", "", description])
            lines.extend(markdown_list("Scope", task.get("scope")))
            lines.extend(markdown_list("Acceptance", task.get("acceptance_criteria")))
            lines.extend(markdown_list("Test Steps", task.get("test_steps")))
            notes = str(task.get("notes", "")).strip()
            if notes:
                lines.extend(["", "Notes:", "", notes])
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def dashboard_tasks_json(tasks: list[Task]) -> str:
    return json.dumps(
        [
            {
                "id": task.get("id"),
                "title": task.get("title", ""),
                "status": task.get("status", "pending"),
                "priority": task.get("priority", ""),
                "category": task.get("category", ""),
                "stage": task.get("stage", ""),
                "stage_gate": bool(task.get("stage_gate", False)),
                "dependencies": task.get("dependencies", []),
                "description": task.get("description", ""),
                "scope": task.get("scope", []),
                "acceptance": task.get("acceptance_criteria", []),
                "test_steps": task.get("test_steps", []),
                "notes": task.get("notes", ""),
            }
            for task in tasks
        ],
        ensure_ascii=False,
        separators=(",", ":"),
    ).replace("</", "<\\/")


def generated_dashboard(config: TaskosConfig, tasks: list[Task]) -> str:
    title = escape(f"{config.project_name} Task Board")
    subtitle = escape(
        f"Generated from {config.tasks_file}. Bright orange = can start, blue = in work, green = done, red = blocked, gray = waiting."
    )
    task_json = dashboard_tasks_json(tasks)
    priority_order = json.dumps(list(config.priority_order), ensure_ascii=False)
    dashboard_dir = posixpath.dirname(config.generated_dashboard.replace("\\", "/")) or "."
    tasks_file_ref = json.dumps(
        posixpath.relpath(config.tasks_file.replace("\\", "/"), dashboard_dir),
        ensure_ascii=False,
    )

    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{title}</title>
  <style>
    :root {{
      color-scheme: light;
      --bg: #f5f7fb;
      --panel: #ffffff;
      --panel-soft: #f8fafc;
      --text: #172033;
      --muted: #667085;
      --border: #d6dce8;
      --done: #15803d;
      --ready: #f97316;
      --blocked: #b91c1c;
      --working: #2563eb;
      --pending: #64748b;
      --focus: #2563eb;
    }}
    * {{ box-sizing: border-box; }}
    html {{
      height: 100%;
    }}
    body {{
      height: 100%;
      margin: 0;
      background: var(--bg);
      color: var(--text);
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      display: flex;
      flex-direction: column;
      overflow: hidden;
    }}
    header {{
      z-index: 10;
      flex: 0 0 auto;
      border-bottom: 1px solid var(--border);
      background: rgba(245, 247, 251, 0.96);
      backdrop-filter: blur(10px);
      padding: 8px 14px;
    }}
    .header-top {{
      display: flex;
      align-items: baseline;
      gap: 10px;
      min-width: 0;
    }}
    h1 {{
      margin: 0;
      font-size: 17px;
      line-height: 1.2;
      letter-spacing: 0;
      white-space: nowrap;
    }}
    .subtitle {{
      margin: 0;
      color: var(--muted);
      font-size: 12px;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }}
    .toolbar {{
      display: grid;
      grid-template-columns: minmax(220px, 330px) auto minmax(0, 1fr);
      gap: 8px;
      align-items: center;
      margin-top: 7px;
    }}
    input[type="search"] {{
      width: 100%;
      height: 32px;
      border: 1px solid var(--border);
      border-radius: 8px;
      background: var(--panel);
      color: var(--text);
      padding: 0 12px;
      font: inherit;
      outline: none;
    }}
    input[type="search"]:focus {{
      border-color: var(--focus);
      box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.14);
    }}
    .zoom-controls {{
      display: inline-flex;
      align-items: center;
      gap: 4px;
      white-space: nowrap;
    }}
    .zoom-button {{
      width: 32px;
      height: 32px;
      border: 1px solid var(--border);
      border-radius: 8px;
      background: var(--panel);
      color: var(--text);
      cursor: pointer;
      font-size: 16px;
      font-weight: 800;
      line-height: 1;
    }}
    .zoom-button:hover {{
      border-color: var(--focus);
      box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.12);
    }}
    .zoom-label {{
      min-width: 42px;
      color: var(--muted);
      font-size: 12px;
      font-weight: 800;
      text-align: center;
    }}
    .stats, .filters {{
      display: flex;
      flex-wrap: nowrap;
      gap: 8px;
      align-items: center;
      overflow-x: auto;
      scrollbar-width: thin;
    }}
    .filters {{ margin-top: 6px; padding-bottom: 2px; }}
    .filter-group {{
      display: contents;
    }}
    .filter-label {{
      display: inline-flex;
      align-items: center;
      color: var(--muted);
      font-size: 12px;
      font-weight: 800;
      min-height: 30px;
    }}
    .stage-summary {{
      display: flex;
      flex-wrap: nowrap;
      gap: 8px;
      margin-top: 6px;
      overflow-x: auto;
      scrollbar-width: thin;
      padding-bottom: 2px;
    }}
    .pill, .filter {{
      display: inline-flex;
      gap: 7px;
      align-items: center;
      min-height: 30px;
      border: 1px solid var(--border);
      border-radius: 999px;
      background: var(--panel);
      color: var(--muted);
      font-size: 12px;
      line-height: 1;
      padding: 6px 10px;
      white-space: nowrap;
    }}
    .pill.compact {{
      min-height: 26px;
      padding: 5px 9px;
    }}
    .pill.status-ready {{
      border-color: rgba(249, 115, 22, 0.62);
      background: #ffedd5;
      color: #9a3412;
      font-weight: 900;
    }}
    .pill.status-working {{
      border-color: rgba(37, 99, 235, 0.42);
      background: #dbeafe;
      color: #1d4ed8;
      font-weight: 900;
    }}
    .pill.status-done {{
      border-color: rgba(21, 128, 61, 0.38);
      background: #dcfce7;
      color: #166534;
      font-weight: 900;
    }}
    .pill.status-blocked {{
      border-color: rgba(185, 28, 28, 0.35);
      background: #fee2e2;
      color: #991b1b;
      font-weight: 900;
    }}
    .pill.status-pending {{
      border-color: rgba(100, 116, 139, 0.35);
      background: #f1f5f9;
      color: #475569;
      font-weight: 900;
    }}
    .filter {{
      cursor: pointer;
      color: var(--text);
    }}
    .filter input {{ accent-color: var(--focus); }}
    .filter-drawer {{
      margin-top: 4px;
    }}
    .filter-drawer summary {{
      display: inline-flex;
      align-items: center;
      min-height: 26px;
      border: 1px solid var(--border);
      border-radius: 999px;
      background: var(--panel);
      color: var(--text);
      cursor: pointer;
      font-size: 12px;
      font-weight: 800;
      list-style: none;
      padding: 5px 10px;
      user-select: none;
      width: fit-content;
    }}
    .filter-drawer summary::-webkit-details-marker {{
      display: none;
    }}
    main {{
      display: grid;
      grid-template-columns: minmax(0, 1fr) 370px;
      flex: 1 1 auto;
      min-height: 0;
      overflow: hidden;
    }}
    main.details-closed {{
      grid-template-columns: minmax(0, 1fr);
    }}
    main.details-closed aside {{
      display: none;
    }}
    .board {{
      min-height: 0;
      height: 100%;
      overflow: auto;
      padding: 24px;
      cursor: grab;
      overscroll-behavior: contain;
    }}
    .board.dragging {{
      cursor: grabbing;
      user-select: none;
    }}
    .columns {{
      display: flex;
      align-items: flex-start;
      gap: 18px;
      min-width: max-content;
    }}
    .column {{
      width: 270px;
      flex: 0 0 270px;
    }}
    .column h2 {{
      position: sticky;
      top: 0;
      z-index: 2;
      margin: 0 0 10px;
      border: 1px solid var(--border);
      border-radius: 8px;
      background: rgba(255, 255, 255, 0.94);
      color: var(--muted);
      font-size: 12px;
      letter-spacing: 0.04em;
      padding: 8px 10px;
      text-transform: uppercase;
    }}
    .card {{
      position: relative;
      margin: 0 0 10px;
      border: 1px solid var(--border);
      border-left: 5px solid #94a3b8;
      border-radius: 8px;
      background: var(--panel);
      box-shadow: 0 8px 22px rgba(15, 23, 42, 0.07);
      cursor: pointer;
      padding: 34px 10px 10px;
      user-select: none;
      overflow: hidden;
    }}
    .card:hover, .card.selected {{
      border-color: var(--focus);
      box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.16), 0 14px 32px rgba(15, 23, 42, 0.12);
    }}
    .card.related {{
      border-color: #60a5fa;
      box-shadow: 0 0 0 2px rgba(96, 165, 250, 0.24), 0 12px 28px rgba(15, 23, 42, 0.10);
    }}
    .card.dimmed {{
      opacity: 0.34;
      filter: saturate(0.65);
      box-shadow: none;
    }}
    .card.dimmed:hover {{
      opacity: 0.72;
      filter: none;
    }}
    .card.done {{
      border-left-color: var(--done);
      border-color: rgba(21, 128, 61, 0.40);
      background: linear-gradient(135deg, #dcfce7 0%, #ffffff 72%);
    }}
    .card.in_progress {{
      border-left-color: var(--working);
      border-color: rgba(37, 99, 235, 0.42);
      background: linear-gradient(135deg, #dbeafe 0%, #ffffff 72%);
      box-shadow: 0 0 0 2px rgba(37, 99, 235, 0.18), 0 10px 26px rgba(30, 64, 175, 0.12);
    }}
    .card.blocked {{
      border-left-color: var(--blocked);
      border-color: rgba(185, 28, 28, 0.38);
      background: linear-gradient(135deg, #fee2e2 0%, #ffffff 72%);
    }}
    .card.pending {{
      border-left-color: var(--pending);
      background: linear-gradient(135deg, #f8fafc 0%, #ffffff 72%);
    }}
    .card.dependency-ready {{
      border-color: rgba(249, 115, 22, 0.72);
      border-left-color: var(--ready);
      background: linear-gradient(135deg, #fed7aa 0%, #fff7ed 48%, #ffffff 78%);
      box-shadow: 0 0 0 4px rgba(249, 115, 22, 0.30), 0 14px 34px rgba(194, 65, 12, 0.18);
    }}
    .status-ribbon {{
      position: absolute;
      inset: 0 0 auto 0;
      display: flex;
      align-items: center;
      justify-content: space-between;
      min-height: 24px;
      padding: 5px 10px;
      color: #ffffff;
      font-size: 10px;
      font-weight: 900;
      letter-spacing: 0.08em;
      text-transform: uppercase;
    }}
    .status-ribbon.ready {{ background: var(--ready); }}
    .status-ribbon.working {{ background: var(--working); }}
    .status-ribbon.done {{ background: var(--done); }}
    .status-ribbon.blocked {{ background: var(--blocked); }}
    .status-ribbon.waiting {{ background: var(--pending); }}
    .status-ribbon .status-id {{
      opacity: 0.88;
    }}
    .idline {{
      display: flex;
      justify-content: space-between;
      gap: 8px;
      font-size: 12px;
      font-weight: 800;
      letter-spacing: 0.02em;
      margin-bottom: 7px;
    }}
    .title {{
      min-height: 38px;
      font-size: 13px;
      line-height: 1.28;
    }}
    .tags, .deps {{
      display: flex;
      flex-wrap: wrap;
      gap: 5px;
      margin-top: 8px;
    }}
    .tag {{
      border-radius: 999px;
      background: var(--panel-soft);
      color: var(--muted);
      font-size: 11px;
      line-height: 1;
      padding: 4px 7px;
    }}
    .tag.dependency-ready {{ background: #ffedd5; color: #9a3412; font-weight: 900; }}
    .tag.done {{ color: var(--done); font-weight: 800; }}
    .tag.in_progress {{ color: var(--working); font-weight: 800; }}
    .tag.blocked {{ color: var(--blocked); font-weight: 800; }}
    .tag.state {{ font-weight: 900; }}
    .tag.state.ready {{ background: #ffedd5; color: #9a3412; }}
    .tag.state.working {{ background: #dbeafe; color: #1d4ed8; }}
    .tag.state.done {{ background: #dcfce7; color: #166534; }}
    .tag.state.blocked {{ background: #fee2e2; color: #991b1b; }}
    .tag.state.waiting {{ background: #f1f5f9; color: #475569; }}
    .tag.stage {{ color: #2563eb; font-weight: 800; }}
    .tag.stage-gate {{ color: #7c2d12; font-weight: 800; }}
    .dep {{
      border-radius: 999px;
      background: #eef2ff;
      color: #3730a3;
      font-size: 10px;
      font-weight: 800;
      line-height: 1;
      padding: 4px 6px;
    }}
    .dep.done {{ background: #dcfce7; color: #166534; }}
    .dep.in_progress {{ background: #ffedd5; color: #c2410c; }}
    .dep.blocked {{ background: #fee2e2; color: #991b1b; }}
    aside {{
      overflow: auto;
      border-left: 1px solid var(--border);
      background: var(--panel);
      padding: 22px;
    }}
    .details-header {{
      display: flex;
      align-items: flex-start;
      justify-content: space-between;
      gap: 12px;
    }}
    .details-close {{
      width: 30px;
      height: 30px;
      flex: 0 0 30px;
      border: 1px solid var(--border);
      border-radius: 8px;
      background: var(--panel-soft);
      color: var(--muted);
      cursor: pointer;
      font: inherit;
      line-height: 1;
    }}
    .details-close:hover {{
      border-color: var(--focus);
      color: var(--text);
    }}
    aside h2 {{
      margin: 0 0 8px;
      font-size: 18px;
      line-height: 1.25;
    }}
    aside p {{
      color: var(--muted);
      font-size: 13px;
      line-height: 1.5;
    }}
    .section {{
      border-top: 1px solid var(--border);
      margin-top: 14px;
      padding-top: 14px;
    }}
    .section h3 {{
      margin: 0 0 8px;
      color: var(--muted);
      font-size: 12px;
      letter-spacing: 0.04em;
      text-transform: uppercase;
    }}
    ul {{
      margin: 0;
      padding-left: 18px;
      color: var(--text);
      font-size: 13px;
      line-height: 1.45;
    }}
    .refresh-status {{
      color: var(--muted);
      font-size: 12px;
    }}
    @media (max-width: 980px) {{
      .header-top {{ align-items: flex-start; flex-direction: column; gap: 2px; }}
      .toolbar, main {{ grid-template-columns: 1fr; }}
      .zoom-controls {{ justify-content: flex-start; }}
      header {{ padding: 7px 10px; }}
      aside {{ border-left: 0; border-top: 1px solid var(--border); }}
      main.details-closed aside {{ display: none; }}
    }}
  </style>
</head>
<body>
  <header>
    <div class="header-top">
      <h1>{title}</h1>
      <p class="subtitle">{subtitle}</p>
    </div>
    <div class="toolbar">
      <input id="search" type="search" placeholder="Search by id, title, stage, category, or dependency" />
      <div class="zoom-controls" aria-label="Board zoom controls">
        <button class="zoom-button" id="zoomOut" type="button" title="Zoom out">-</button>
        <span class="zoom-label" id="zoomLabel">100%</span>
        <button class="zoom-button" id="zoomIn" type="button" title="Zoom in">+</button>
      </div>
      <div>
        <div class="stats" id="stats"></div>
        <div class="stage-summary" id="stageSummary"></div>
        <details class="filter-drawer">
          <summary>Filters</summary>
          <div class="filters" id="filters"></div>
        </details>
        <div class="refresh-status" id="refreshStatus"></div>
      </div>
    </div>
  </header>
  <main id="layout">
    <section class="board" id="board">
      <div class="columns" id="columns"></div>
    </section>
    <aside id="details"></aside>
  </main>
  <script>
    const EMBEDDED_TASKS = {task_json};
    const PRIORITY_ORDER = {priority_order};
    const TASKS_FILE = {tasks_file_ref};
    const SCROLL_STORAGE_KEY = "taskBoardScrollPosition";
    let TASKS = normalizeTasks(EMBEDDED_TASKS);
    let byId = new Map(TASKS.map((task) => [task.id, task]));
    let priorities = priorityList(TASKS);
    let stages = stageList(TASKS);
    const selectedPriorities = new Set(priorities);
    const selectedStages = new Set(stages);
    const layoutEl = document.querySelector("#layout");
    const boardEl = document.querySelector("#board");
    const searchEl = document.querySelector("#search");
    const zoomOutEl = document.querySelector("#zoomOut");
    const zoomInEl = document.querySelector("#zoomIn");
    const zoomLabelEl = document.querySelector("#zoomLabel");
    const filtersEl = document.querySelector("#filters");
    const columnsEl = document.querySelector("#columns");
    const statsEl = document.querySelector("#stats");
    const stageSummaryEl = document.querySelector("#stageSummary");
    const detailsEl = document.querySelector("#details");
    const refreshStatusEl = document.querySelector("#refreshStatus");
    let selectedId = "";
    let detailsOpen = false;
    let suppressCardClick = false;
    let boardZoom = loadZoom();
    let lastTaskSignature = taskSignature(TASKS);
    let fetchFailureCount = 0;
    let scrollSaveFrame = 0;

    function normalizeTasks(raw) {{
      const list = Array.isArray(raw) ? raw : (raw?.tasks ?? []);
      return list.map((task) => ({{
        id: task.id,
        title: task.title ?? "",
        status: task.status ?? "pending",
        priority: task.priority ?? "",
        category: task.category ?? "",
        stage: task.stage ?? "Unstaged",
        stage_gate: Boolean(task.stage_gate),
        dependencies: Array.isArray(task.dependencies) ? task.dependencies : [],
        description: task.description ?? "",
        scope: Array.isArray(task.scope) ? task.scope : [],
        acceptance: Array.isArray(task.acceptance) ? task.acceptance : (task.acceptance_criteria ?? []),
        test_steps: Array.isArray(task.test_steps) ? task.test_steps : [],
        notes: task.notes ?? "",
      }}));
    }}

    function priorityList(tasks) {{
      return [...new Set([...PRIORITY_ORDER, ...tasks.map((task) => task.priority).filter(Boolean)])];
    }}

    function stageList(tasks) {{
      return [...new Set(tasks.map((task) => task.stage).filter(Boolean))];
    }}

    function taskSignature(tasks) {{
      return JSON.stringify(tasks);
    }}

    function escapeHtml(value) {{
      return String(value ?? "")
        .replaceAll("&", "&amp;")
        .replaceAll("<", "&lt;")
        .replaceAll(">", "&gt;")
        .replaceAll('"', "&quot;")
        .replaceAll("'", "&#039;");
    }}

    function isReady(task) {{
      return task.status === "pending" && task.dependencies.every((id) => byId.get(id)?.status === "done");
    }}

    function executionState(task) {{
      if (isReady(task)) return "ready";
      if (task.status === "in_progress") return "working";
      if (task.status === "done") return "done";
      if (task.status === "blocked") return "blocked";
      return "waiting";
    }}

    function executionLabel(task) {{
      const state = executionState(task);
      return {{
        ready: "Can start",
        working: "In work",
        done: "Done",
        blocked: "Blocked",
        waiting: "Waiting",
      }}[state] ?? state;
    }}

    function loadZoom() {{
      try {{
        const value = Number(window.localStorage.getItem("taskBoardZoom"));
        return Number.isFinite(value) ? value : 1;
      }} catch (error) {{
        return 1;
      }}
    }}

    function setZoom(value) {{
      boardZoom = Math.max(0.7, Math.min(1.4, Number(value) || 1));
      columnsEl.style.zoom = String(boardZoom);
      zoomLabelEl.textContent = `${{Math.round(boardZoom * 100)}}%`;
      try {{
        window.localStorage.setItem("taskBoardZoom", String(boardZoom));
      }} catch (error) {{
        // Static file mode can deny storage; zoom still works for this session.
      }}
    }}

    function stepZoom(delta) {{
      setZoom(Math.round((boardZoom + delta) * 10) / 10);
    }}

    function relatedTaskIds(taskId) {{
      const related = new Set();
      if (!taskId || !byId.has(taskId)) return related;
      related.add(taskId);

      function visitDependencies(id) {{
        const task = byId.get(id);
        if (!task) return;
        for (const dependencyId of task.dependencies) {{
          if (related.has(dependencyId)) continue;
          related.add(dependencyId);
          visitDependencies(dependencyId);
        }}
      }}

      function visitDependents(id) {{
        for (const task of TASKS) {{
          if (!task.dependencies.includes(id) || related.has(task.id)) continue;
          related.add(task.id);
          visitDependents(task.id);
        }}
      }}

      visitDependencies(taskId);
      visitDependents(taskId);
      return related;
    }}

    function depthFor(task, memo = new Map(), visiting = new Set()) {{
      if (memo.has(task.id)) return memo.get(task.id);
      if (visiting.has(task.id)) return 0;
      visiting.add(task.id);
      const depth = task.dependencies.length
        ? Math.max(...task.dependencies.map((id) => byId.has(id) ? depthFor(byId.get(id), memo, visiting) : 0)) + 1
        : 0;
      visiting.delete(task.id);
      memo.set(task.id, depth);
      return depth;
    }}

    function visibleTasks() {{
      const query = searchEl.value.trim().toLowerCase();
      return TASKS.filter((task) => {{
        if (!selectedPriorities.has(task.priority)) return false;
        if (!selectedStages.has(task.stage)) return false;
        if (!query) return true;
        return `${{task.id}} ${{task.title}} ${{task.stage}} ${{task.category}} ${{task.status}} ${{task.dependencies.join(" ")}}`
          .toLowerCase()
          .includes(query);
      }});
    }}

    function renderStats() {{
      let dependencyReady = 0;
      let gateDone = 0;
      let gateTotal = 0;
      const counts = TASKS.reduce((acc, task) => {{
        acc[task.status] = (acc[task.status] ?? 0) + 1;
        if (isReady(task)) dependencyReady += 1;
        if (task.stage_gate) {{
          gateTotal += 1;
          if (task.status === "done") gateDone += 1;
        }}
        return acc;
      }}, {{}});
      const waitingPending = Math.max(0, (counts.pending ?? 0) - dependencyReady);
      statsEl.innerHTML = [
        ["Can start", dependencyReady, "status-ready"],
        ["In work", counts.in_progress ?? 0, "status-working"],
        ["Done", counts.done ?? 0, "status-done"],
        ["Blocked", counts.blocked ?? 0, "status-blocked"],
        ["Waiting", waitingPending, "status-pending"],
        ["Total", TASKS.length, ""],
        ["Stage gates", `${{gateDone}}/${{gateTotal}}`, ""],
      ].map(([label, value, className]) => `<span class="pill compact ${{className}}">${{label}}: ${{value}}</span>`).join("");
      const stageRows = stages.map((stage) => {{
        const stageTasks = TASKS.filter((task) => task.stage === stage);
        const done = stageTasks.filter((task) => task.status === "done").length;
        const gate = stageTasks.find((task) => task.stage_gate);
        const gateText = gate ? ` - gate ${{gate.status}}` : "";
        return `<span class="pill compact">${{escapeHtml(stage)}}: ${{done}}/${{stageTasks.length}}${{gateText}}</span>`;
      }});
      stageSummaryEl.innerHTML = stageRows.join("");
    }}

    function renderFilters() {{
      const priorityFilters = priorities
        .map((priority) => `<label class="filter"><input type="checkbox" data-kind="priority" data-value="${{escapeHtml(priority)}}" ${{selectedPriorities.has(priority) ? "checked" : ""}} /> ${{escapeHtml(priority)}}</label>`)
        .join("");
      const stageFilters = stages
        .map((stage) => `<label class="filter"><input type="checkbox" data-kind="stage" data-value="${{escapeHtml(stage)}}" ${{selectedStages.has(stage) ? "checked" : ""}} /> ${{escapeHtml(stage)}}</label>`)
        .join("");
      filtersEl.innerHTML = `<span class="filter-label">Priority</span>${{priorityFilters}}<span class="filter-label">Stage</span>${{stageFilters}}`;
      filtersEl.querySelectorAll("input").forEach((input) => {{
        input.addEventListener("change", () => {{
          const target = input.dataset.kind === "stage" ? selectedStages : selectedPriorities;
          if (input.checked) target.add(input.dataset.value);
          else target.delete(input.dataset.value);
          render();
        }});
      }});
    }}

    function renderCard(task, relatedIds) {{
      const ready = isReady(task);
      const status = task.status;
      const state = executionState(task);
      const stateLabel = executionLabel(task);
      const selected = detailsOpen && task.id === selectedId;
      const related = relatedIds ? relatedIds.has(task.id) : false;
      const dimmed = relatedIds ? !related : false;
      const deps = task.dependencies.length
        ? `<div class="deps">${{task.dependencies.map((id) => {{
            const depStatus = byId.get(id)?.status ?? "missing";
            return `<span class="dep ${{escapeHtml(depStatus)}}">${{escapeHtml(id)}}</span>`;
          }}).join("")}}</div>`
        : "";
      return `<article class="card ${{escapeHtml(status)}} ${{ready ? "dependency-ready" : ""}} ${{selected ? "selected" : ""}} ${{related && !selected ? "related" : ""}} ${{dimmed ? "dimmed" : ""}}" data-id="${{escapeHtml(task.id)}}">
        <div class="status-ribbon ${{escapeHtml(state)}}"><span>${{escapeHtml(stateLabel)}}</span><span class="status-id">${{escapeHtml(task.status)}}</span></div>
        <div class="idline"><span>${{escapeHtml(task.id)}}</span><span>${{escapeHtml(task.priority)}}</span></div>
        <div class="title">${{escapeHtml(task.title)}}</div>
        <div class="tags">
          <span class="tag state ${{escapeHtml(state)}}">${{escapeHtml(stateLabel)}}</span>
          <span class="tag ${{escapeHtml(status)}}">${{escapeHtml(status)}}</span>
          ${{ready ? `<span class="tag dependency-ready">dependency-ready</span>` : ""}}
          ${{task.stage_gate ? `<span class="tag stage-gate">stage gate</span>` : ""}}
          <span class="tag stage">${{escapeHtml(task.stage)}}</span>
          <span class="tag">${{escapeHtml(task.category)}}</span>
        </div>
        ${{deps}}
      </article>`;
    }}

    function renderColumns() {{
      const memo = new Map();
      const groups = new Map();
      const relatedIds = detailsOpen && selectedId ? relatedTaskIds(selectedId) : null;
      for (const task of visibleTasks()) {{
        const depth = depthFor(task, memo);
        if (!groups.has(depth)) groups.set(depth, []);
        groups.get(depth).push(task);
      }}
      columnsEl.innerHTML = [...groups.entries()]
        .sort((a, b) => a[0] - b[0])
        .map(([depth, tasks]) => `<section class="column"><h2>Layer ${{depth}}</h2>${{tasks.map((task) => renderCard(task, relatedIds)).join("")}}</section>`)
        .join("");
      columnsEl.querySelectorAll(".card").forEach((card) => {{
        card.addEventListener("click", () => {{
          if (suppressCardClick) return;
          if (detailsOpen && selectedId === card.dataset.id) {{
            detailsOpen = false;
          }} else {{
            selectedId = card.dataset.id;
            detailsOpen = true;
          }}
          render();
        }});
      }});
    }}

    function section(title, values) {{
      if (!values || (Array.isArray(values) && values.length === 0)) return "";
      const items = Array.isArray(values) ? values : [values];
      return `<div class="section"><h3>${{escapeHtml(title)}}</h3><ul>${{items.map((item) => `<li>${{escapeHtml(item)}}</li>`).join("")}}</ul></div>`;
    }}

    function renderDetails() {{
      if (!detailsOpen) {{
        detailsEl.innerHTML = "";
        return;
      }}
      const task = byId.get(selectedId);
      if (!task) {{
        detailsOpen = false;
        detailsEl.innerHTML = "";
        layoutEl.classList.add("details-closed");
        return;
      }}
      const ready = isReady(task);
      const state = executionState(task);
      const stateLabel = executionLabel(task);
      detailsEl.innerHTML = `<div class="details-header">
          <h2>${{escapeHtml(task.id)}} - ${{escapeHtml(task.title)}}</h2>
          <button class="details-close" type="button" aria-label="Close details">x</button>
        </div>
        <p>${{escapeHtml(task.description || "No description.")}}</p>
        <div class="tags">
          <span class="tag state ${{escapeHtml(state)}}">${{escapeHtml(stateLabel)}}</span>
          <span class="tag ${{escapeHtml(task.status)}}">${{escapeHtml(task.status)}}</span>
          ${{ready ? `<span class="tag dependency-ready">dependency-ready</span>` : ""}}
          ${{task.stage_gate ? `<span class="tag stage-gate">stage gate</span>` : ""}}
          <span class="tag">${{escapeHtml(task.priority)}}</span>
          <span class="tag stage">${{escapeHtml(task.stage)}}</span>
          <span class="tag">${{escapeHtml(task.category)}}</span>
        </div>
        ${{section("Stage", [task.stage, task.stage_gate ? "Stage gate" : "Regular task"])}}
        ${{section("Dependencies", task.dependencies.length ? task.dependencies : ["None"])}}
        ${{section("Scope", task.scope)}}
        ${{section("Acceptance", task.acceptance)}}
        ${{section("Test Steps", task.test_steps)}}
        ${{section("Notes", task.notes ? [task.notes] : [])}}`;
      detailsEl.querySelector(".details-close")?.addEventListener("click", () => {{
        detailsOpen = false;
        render();
      }});
    }}

    function render() {{
      layoutEl.classList.toggle("details-closed", !detailsOpen);
      renderStats();
      renderColumns();
      renderDetails();
    }}

    function setRefreshStatus(value) {{
      if (refreshStatusEl) refreshStatusEl.textContent = value;
    }}

    function numberOrZero(value) {{
      const number = Number(value);
      return Number.isFinite(number) ? number : 0;
    }}

    function readScrollPosition() {{
      try {{
        const raw = window.sessionStorage.getItem(SCROLL_STORAGE_KEY);
        if (!raw) return null;
        const saved = JSON.parse(raw);
        return {{
          left: numberOrZero(saved.left),
          top: numberOrZero(saved.top),
          windowX: numberOrZero(saved.windowX),
          windowY: numberOrZero(saved.windowY),
        }};
      }} catch (error) {{
        return null;
      }}
    }}

    function saveScrollPosition() {{
      try {{
        window.sessionStorage.setItem(SCROLL_STORAGE_KEY, JSON.stringify({{
          left: boardEl.scrollLeft,
          top: boardEl.scrollTop,
          windowX: window.scrollX,
          windowY: window.scrollY,
        }}));
      }} catch (error) {{
        // Static file mode can deny storage; scrolling still works for this session.
      }}
    }}

    function restoreScrollPosition() {{
      const saved = readScrollPosition();
      if (!saved) return;
      window.requestAnimationFrame(() => {{
        const maxLeft = Math.max(0, boardEl.scrollWidth - boardEl.clientWidth);
        const maxTop = Math.max(0, boardEl.scrollHeight - boardEl.clientHeight);
        boardEl.scrollLeft = Math.min(saved.left, maxLeft);
        boardEl.scrollTop = Math.min(saved.top, maxTop);
        window.scrollTo(saved.windowX, saved.windowY);
      }});
    }}

    function scheduleScrollPositionSave() {{
      if (scrollSaveFrame) return;
      scrollSaveFrame = window.requestAnimationFrame(() => {{
        scrollSaveFrame = 0;
        saveScrollPosition();
      }});
    }}

    function updateTasks(raw) {{
      const nextTasks = normalizeTasks(raw);
      const nextSignature = taskSignature(nextTasks);
      if (nextSignature === lastTaskSignature) return false;

      const previousScrollLeft = boardEl.scrollLeft;
      const previousScrollTop = boardEl.scrollTop;
      const previousWindowScrollX = window.scrollX;
      const previousWindowScrollY = window.scrollY;
      const previousSelectedPriorities = new Set(selectedPriorities);
      const previousSelectedStages = new Set(selectedStages);
      TASKS = nextTasks;
      byId = new Map(TASKS.map((task) => [task.id, task]));
      priorities = priorityList(TASKS);
      stages = stageList(TASKS);
      selectedPriorities.clear();
      for (const priority of priorities) {{
        if (previousSelectedPriorities.size === 0 || previousSelectedPriorities.has(priority)) {{
          selectedPriorities.add(priority);
        }}
      }}
      selectedStages.clear();
      for (const stage of stages) {{
        if (previousSelectedStages.size === 0 || previousSelectedStages.has(stage)) {{
          selectedStages.add(stage);
        }}
      }}
      if (selectedId && !byId.has(selectedId)) {{
        selectedId = "";
        detailsOpen = false;
      }}
      if (detailsOpen && !selectedId) detailsOpen = false;
      lastTaskSignature = nextSignature;
      renderFilters();
      render();
      const maxLeft = Math.max(0, boardEl.scrollWidth - boardEl.clientWidth);
      const maxTop = Math.max(0, boardEl.scrollHeight - boardEl.clientHeight);
      boardEl.scrollLeft = Math.min(previousScrollLeft, maxLeft);
      boardEl.scrollTop = Math.min(previousScrollTop, maxTop);
      window.scrollTo(previousWindowScrollX, previousWindowScrollY);
      return true;
    }}

    async function refreshFromTasksFile() {{
      const url = new URL(TASKS_FILE, window.location.href);
      url.searchParams.set("v", String(Date.now()));
      try {{
        const response = await fetch(url, {{ cache: "no-store" }});
        if (!response.ok) throw new Error(`HTTP ${{response.status}}`);
        const changed = updateTasks(await response.json());
        fetchFailureCount = 0;
        setRefreshStatus(changed ? "Auto-refresh: updated" : "Auto-refresh: synced");
        if (window.parent && window.parent !== window) {{
          window.parent.postMessage({{ type: "taskboard:live-refresh" }}, "*");
        }}
      }} catch (error) {{
        fetchFailureCount += 1;
        setRefreshStatus("Auto-refresh: static file mode");
      }}
    }}

    function enableBoardDrag() {{
      let isDown = false;
      let hasDragged = false;
      let startX = 0;
      let startY = 0;
      let startScrollLeft = 0;
      let startScrollTop = 0;

      boardEl.addEventListener("mousedown", (event) => {{
        if (event.button !== 0) return;
        if (event.target.closest("input, button, label, textarea, select")) return;
        isDown = true;
        hasDragged = false;
        startX = event.clientX;
        startY = event.clientY;
        startScrollLeft = boardEl.scrollLeft;
        startScrollTop = boardEl.scrollTop;
        boardEl.classList.add("dragging");
      }});

      window.addEventListener("mousemove", (event) => {{
        if (!isDown) return;
        const dx = event.clientX - startX;
        const dy = event.clientY - startY;
        if (Math.abs(dx) > 4 || Math.abs(dy) > 4) hasDragged = true;
        if (!hasDragged) return;
        event.preventDefault();
        boardEl.scrollLeft = startScrollLeft - dx;
        boardEl.scrollTop = startScrollTop - dy;
      }});

      window.addEventListener("mouseup", () => {{
        if (!isDown) return;
        isDown = false;
        boardEl.classList.remove("dragging");
        if (hasDragged) {{
          suppressCardClick = true;
          window.setTimeout(() => {{
            suppressCardClick = false;
          }}, 0);
        }}
      }});
    }}

    searchEl.addEventListener("input", render);
    zoomOutEl.addEventListener("click", () => stepZoom(-0.1));
    zoomInEl.addEventListener("click", () => stepZoom(0.1));
    boardEl.addEventListener("scroll", scheduleScrollPositionSave, {{ passive: true }});
    window.addEventListener("scroll", scheduleScrollPositionSave, {{ passive: true }});
    window.addEventListener("pagehide", saveScrollPosition);
    document.addEventListener("visibilitychange", () => {{
      if (document.visibilityState === "hidden") saveScrollPosition();
    }});
    enableBoardDrag();
    setZoom(boardZoom);
    renderFilters();
    render();
    restoreScrollPosition();
    refreshFromTasksFile();
    window.setInterval(refreshFromTasksFile, 3000);
  </script>
</body>
</html>
"""


def generated_dashboard_wrapper(config: TaskosConfig, iframe_src: str) -> str:
    title = escape(f"{config.project_name} Task Board")
    iframe_json = json.dumps(iframe_src)
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{title}</title>
  <style>
    html, body, iframe {{
      width: 100%;
      height: 100%;
      margin: 0;
    }}
    body {{
      overflow: hidden;
      background: #f5f7fb;
    }}
    iframe {{
      display: block;
      border: 0;
    }}
  </style>
</head>
<body>
  <iframe id="taskBoardFrame" title="{title}"></iframe>
  <script>
    const frame = document.querySelector("#taskBoardFrame");
    const iframeSrc = {iframe_json};

    function loadFrame() {{
      frame.src = iframeSrc + "?v=" + Date.now();
    }}

    loadFrame();
  </script>
</body>
</html>
"""
