from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter, ImageFont


ROOT = Path(__file__).resolve().parents[1]
ASSET_DIR = ROOT / "backend" / "witcher_larp" / "web" / "lord" / "assets"
REPORT_DIR = ROOT / "reports" / "map-debug-crops"
LAYOUT_PATH = ASSET_DIR / "lord_map_layout.json"
MAP_NODES_PATH = ROOT / "data" / "seed" / "map_nodes.csv"
MAP_EDGES_PATH = ROOT / "data" / "seed" / "map_edges.csv"

DEFAULT_PREFIX = "lord_map_ai_strict_v2"
DISPLAY_WIDTH = 3172

TYPE_NAMES = {
    "residence": "lord starting point inside the main castle",
    "fort": "small frontier fort",
    "field": "field or farmland",
    "village_barn": "barn village",
    "resource_city": "well market",
    "magic_city": "magic landmark",
    "science_city": "manufactory",
    "forest": "forest or garden grove",
    "lake": "lake or pond",
    "swamp": "swamp",
    "mountain": "mountain ridge or watch cliff",
}

GUIDE_COLORS = {
    "residence": (215, 85, 66),
    "fort": (82, 139, 216),
    "field": (218, 180, 70),
    "village_barn": (184, 116, 64),
    "resource_city": (222, 204, 112),
    "magic_city": (143, 91, 216),
    "science_city": (129, 155, 148),
    "forest": (75, 154, 90),
    "lake": (70, 153, 190),
    "swamp": (54, 104, 84),
    "mountain": (166, 163, 146),
}


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Prepare and upscale a strict OpenRouter-generated lord map image.",
    )
    parser.add_argument("--prefix", default=DEFAULT_PREFIX)
    parser.add_argument(
        "--input",
        type=Path,
        default=None,
        help="Raw OpenRouter image. Defaults to backend lord assets/<prefix>_openrouter_raw.png.",
    )
    parser.add_argument("--prepare-only", action="store_true")
    args = parser.parse_args()

    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    layout = json.loads(LAYOUT_PATH.read_text(encoding="utf-8"))
    seed_nodes = load_seed_nodes()
    seed_edges = load_seed_edges()
    prefix = args.prefix

    prompt_path = REPORT_DIR / f"{prefix}-openrouter-prompt.md"
    skeleton_path = REPORT_DIR / f"{prefix}-skeleton-guide.png"
    annotated_path = REPORT_DIR / f"{prefix}-annotated-guide.png"
    write_prompt(prompt_path, layout, seed_nodes, seed_edges)
    write_skeleton_guide(skeleton_path, layout, seed_nodes, labels=False)
    write_skeleton_guide(annotated_path, layout, seed_nodes, labels=True)

    if args.prepare_only:
        print(f"prompt: {prompt_path}")
        print(f"skeleton: {skeleton_path}")
        print(f"annotated: {annotated_path}")
        return

    input_path = args.input or ASSET_DIR / f"{prefix}_openrouter_raw.png"
    if not input_path.exists():
        raise FileNotFoundError(
            f"Raw OpenRouter image not found: {input_path}. Run OpenRouter generation first."
        )

    target_size = (int(layout["canvas"]["width"]), int(layout["canvas"]["height"]))
    raw = Image.open(input_path).convert("RGB")
    clean = fit_preserve(raw, target_size)
    clean = finish_upscale(clean)

    png_path = ASSET_DIR / f"{prefix}_clean_generated.png"
    webp_path = ASSET_DIR / f"{prefix}_clean_generated.webp"
    manifest_path = ASSET_DIR / f"{prefix}_manifest.json"
    save_png(clean, png_path)
    save_display_webp(clean, webp_path)
    manifest_path.write_text(
        json.dumps(
            {
                "prefix": prefix,
                "layout_version": layout["version"],
                "layout_mode": layout["mode"],
                "source_raw": str(input_path.relative_to(ROOT)).replace("\\", "/"),
                "final_asset": str(png_path.relative_to(ROOT)).replace("\\", "/"),
                "display_asset": str(webp_path.relative_to(ROOT)).replace("\\", "/"),
                "prompt": str(prompt_path.relative_to(ROOT)).replace("\\", "/"),
                "skeleton_guide": str(skeleton_path.relative_to(ROOT)).replace("\\", "/"),
                "annotated_guide": str(annotated_path.relative_to(ROOT)).replace("\\", "/"),
                "note": "Roads are expected to be generated by the model itself; no postprocess road overlay is applied.",
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"asset: {png_path}")
    print(f"display: {webp_path}")
    print(f"manifest: {manifest_path}")


def load_seed_nodes() -> dict[str, dict[str, str]]:
    with MAP_NODES_PATH.open(encoding="utf-8", newline="") as handle:
        return {row["node_id"]: row for row in csv.DictReader(handle)}


def load_seed_edges() -> list[dict[str, str]]:
    with MAP_EDGES_PATH.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def write_prompt(
    target: Path,
    layout: dict,
    seed_nodes: dict[str, dict[str, str]],
    seed_edges: list[dict[str, str]],
) -> None:
    width = int(layout["canvas"]["width"])
    height = int(layout["canvas"]["height"])
    playable_nodes = [
        (node_id, seed_nodes[node_id], layout["nodes"][node_id])
        for node_id in layout["nodes"]
        if seed_nodes[node_id]["zone_status"] != "no_play_excluded"
    ]
    residences = [item for item in playable_nodes if item[1]["node_type"] == "residence"]
    territories = [item for item in playable_nodes if item[1]["node_type"] != "residence"]

    node_lines = []
    for node_id, seed, node in playable_nodes:
        node_lines.append(
            f"- {seed['name']}: {TYPE_NAMES.get(seed['node_type'], seed['node_type'])}, "
            f"position x={int(node['x']) / width:.3f}, y={int(node['y']) / height:.3f}."
        )

    edge_lines = []
    for edge in seed_edges:
        from_seed = seed_nodes[edge["from_node_id"]]
        to_seed = seed_nodes[edge["to_node_id"]]
        edge_lines.append(
            f"- {from_seed['name']} to {to_seed['name']} (MP {edge['mp_cost']})"
        )

    target.write_text(
        "\n".join(
            [
                "# Strict OpenRouter prompt: generated lord map",
                "",
                "Use the attached skeleton image as a private composition and road-graph guide only.",
                "Do not copy the skeleton's colored dots, plain lines, labels, debug style, symbols, or technical look.",
                "",
                "Generate one finished original high-end hand-painted dark fantasy strategy map background.",
                "The map must contain exactly one large main central castle/manor. Inside that main castle, show exactly four distinct lord starting points as four courtyards/wings/gate rooms arranged around the center. They are the four graph starts, not four separate castles.",
                f"Around the castle, paint exactly {len(territories)} non-start territories, each as a visible themed landmark. Together with the {len(residences)} starts, this makes exactly {len(playable_nodes)} playable graph points.",
                "",
                "Road requirements are strict:",
                f"- Paint exactly {len(seed_edges)} road connections, matching the road graph listed below. The roads must be part of the generated artwork itself, as natural dirt or stone medieval roads.",
                "- The attached skeleton's beige lines are the complete road network. Translate those lines into painted roads; do not invent any road outside that network.",
                "- Preserve the skeleton topology exactly: a road can bend organically, but it must begin at one listed graph point and end at the paired listed graph point.",
                "- Do not create visual junctions, crossroads, Y-splits, roundabouts or branching points unless that junction is one of the 23 playable landmarks listed below.",
                "- If a road visually touches a place, that place must be one of that road's two endpoints from the road graph.",
                "- No extra decorative roads, side paths, shortcuts, loops, forks, highways, trails, or dead-end tracks.",
                "- The roads may curve naturally and need not copy the skeleton line shape, but every road must connect the same two named places and only those two places.",
                "- Roads must not cross each other.",
                "- Roads must not pass through the body of the main central castle/manor. Roads from starting courtyards may leave through gates but should not cut through the building.",
                "- The well market connects to the northern/eastern fort gateway, the river start, and the east village. It does not connect to the oat field.",
                "",
                "Territory list and approximate placement:",
                *node_lines,
                "",
                "Exact road graph, no other roads:",
                *edge_lines,
                "",
                "Art direction:",
                "- Grim Slavic medieval fantasy, Witcher-like mood without using official Witcher assets.",
                "- Top-down/isometric painted strategy map, readable landmarks, rich terrain, no UI frame.",
                "- Fields, forts, forests, lakes, swamp, mountains, well market, magic stones, manufactory and villages should be thematically obvious.",
                "- Leave calm clearings at each graph point for later circular game markers, but do not draw markers.",
                "- No text, no readable letters, no numbers, no labels, no flags with symbols, no ownership colors, no dotted routes, no technical graph overlay, no green debug lines, no watermarks.",
                "",
                "Negative prompt: extra roads, extra castles, duplicate castles, road through central castle, crossed roads, labels, readable words, map pins, colored circles, UI buttons, modern roads, modern buildings, sci-fi, flat vector diagram, technical blueprint.",
            ]
        )
        + "\n",
        encoding="utf-8",
    )


def write_skeleton_guide(
    target: Path,
    layout: dict,
    seed_nodes: dict[str, dict[str, str]],
    *,
    labels: bool,
) -> None:
    scale = 1800 / int(layout["canvas"]["width"])
    width = 1800
    height = round(int(layout["canvas"]["height"]) * scale)
    image = Image.new("RGB", (width, height), (36, 34, 29))
    draw = ImageDraw.Draw(image)

    central = layout.get("central_house") or {}
    if central:
        box = (
            round(int(central["x"]) * scale),
            round(int(central["y"]) * scale),
            round((int(central["x"]) + int(central["w"])) * scale),
            round((int(central["y"]) + int(central["h"])) * scale),
        )
        draw.rectangle(box, outline=(170, 110, 76), width=4, fill=(74, 55, 42))

    for edge in layout["edges"].values():
        points = [(round(x * scale), round(y * scale)) for x, y in edge["points"]]
        draw.line(points, fill=(211, 188, 119), width=5, joint="curve")

    font = ImageFont.load_default()
    for node_id, node in layout["nodes"].items():
        seed = seed_nodes[node_id]
        if seed["zone_status"] == "no_play_excluded":
            continue
        x = round(int(node["x"]) * scale)
        y = round(int(node["y"]) * scale)
        radius = 13 if seed["node_type"] == "residence" else 10
        color = GUIDE_COLORS.get(seed["node_type"], (220, 200, 140))
        draw.ellipse((x - radius, y - radius, x + radius, y + radius), fill=color, outline=(249, 233, 174), width=2)
        if labels:
            draw.text((x + radius + 5, y - radius), seed["name"], fill=(248, 236, 200), font=font)

    if labels:
        draw.text(
            (20, 20),
            "Reference only: do not render dots/labels; render only thematic landmarks and matching roads.",
            fill=(248, 236, 200),
            font=font,
        )

    image.save(target, "PNG", compress_level=6)


def fit_cover(image: Image.Image, target_size: tuple[int, int]) -> Image.Image:
    target_width, target_height = target_size
    scale = max(target_width / image.width, target_height / image.height)
    resized = image.resize(
        (math.ceil(image.width * scale), math.ceil(image.height * scale)),
        Image.Resampling.LANCZOS,
    )
    left = max(0, (resized.width - target_width) // 2)
    top = max(0, (resized.height - target_height) // 2)
    return resized.crop((left, top, left + target_width, top + target_height))


def fit_preserve(image: Image.Image, target_size: tuple[int, int]) -> Image.Image:
    target_width, target_height = target_size
    scale = min(target_width / image.width, target_height / image.height)
    foreground = image.resize(
        (math.floor(image.width * scale), math.floor(image.height * scale)),
        Image.Resampling.LANCZOS,
    )
    background = fit_cover(image, target_size).filter(ImageFilter.GaussianBlur(34))
    overlay = Image.new("RGB", target_size, (0, 0, 0))
    overlay.paste(background)
    left = (target_width - foreground.width) // 2
    top = (target_height - foreground.height) // 2
    overlay.paste(foreground, (left, top))
    return overlay


def finish_upscale(image: Image.Image) -> Image.Image:
    image = image.filter(ImageFilter.UnsharpMask(radius=1.6, percent=125, threshold=3))
    vignette = Image.new("RGBA", image.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(vignette)
    width, height = image.size
    border = round(min(width, height) * 0.11)
    for step in range(border, 0, -18):
        alpha = round(58 * (1 - step / border) ** 1.8)
        draw.rectangle((step, step, width - step, height - step), outline=(8, 7, 5, alpha), width=26)
    result = image.convert("RGBA")
    result.alpha_composite(vignette.filter(ImageFilter.GaussianBlur(34)))
    return result.convert("RGB")


def save_png(image: Image.Image, target: Path) -> None:
    temp = target.with_name(f"{target.name}.tmp")
    temp.unlink(missing_ok=True)
    image.save(temp, "PNG", compress_level=6)
    temp.replace(target)


def save_display_webp(image: Image.Image, target: Path) -> None:
    height = round(image.height * (DISPLAY_WIDTH / image.width))
    display = image.resize((DISPLAY_WIDTH, height), Image.Resampling.LANCZOS)
    temp = target.with_name(f"{target.name}.tmp")
    temp.unlink(missing_ok=True)
    display.save(temp, "WEBP", quality=92, method=6)
    temp.replace(target)


if __name__ == "__main__":
    main()
